### PR TITLE
✨ Allow guest to view articles created by a user

### PR DESCRIPTION
**Pull request by Esseme**
Before, a guest wouldn't be able to view articles created by a user.
Now, a guest can simply navigate to any user's profile and they will
view the articles created by that user.

### CODE REVIEW

**Comment by Esseme** [comment]
[Have a personalised feed](https://trello.com/c/Bz3XImCL/7-have-a-personalised-feed)

**Comment by gkosmo** [comment]
Hi @Esseme, 

It looks good :+1:  
I have some feedback and opinions to share. 

I'm not sure I'd user the `class UsersController < Clearance::UsersController`  - 
This might be a very personal take - but I feel that a  clearance controller might be concerned only with registring/signing in a user, not with showing its articles. Hence I would have gone with a `Profiles` controller or `UserArticles` or something else. 
 
Then, it would maybe be good to add as a ticket a way to maybe "slugify" the users :thinking: ,
I'm just thinking about the experience of sharing a user url and the user is identified by a number instead of by some kind of identifier we understand. 

Finally, I have a question on the article card, again about the user experience, is the `edit` button maybe a bit frustrating ? 
Since only the user that created the article can access it, I feel like it's a button that shoulRoutingErrordn't exist on that page.

Also,  and it might not be related to this PR, the `sign in` button doesn't work :sweat_smile:

**Comment by Esseme** [comment]
Hello @gkosmo,

I appreciate your feedback.
We had discussed the controller with @purinkle  and decided to change it later.

Good point on "slugging" the user. I was considering using the [friendly_id](https://github.com/norman/friendly_id) gem.
With the `edit button` on the article card, I am looking to only show it to the author of the article. 
So, it shall be removed for now.

The `sign in` button is going to be fixed in a separate PR.

**Comment by gkosmo** [comment]
:rocket:   
Super !! 

BTW, I'm grateful that you keep on adding me as a reviewer as I love to see how you're progressing

**Review by purinkle — COMMENTED** [review]
:exploding_head: LGTM!

**Pull request merged**
